// Generated by gencpp from file max_position_estimator/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MAX_POSITION_ESTIMATOR_MESSAGE_ADDTWOINTS_H
#define MAX_POSITION_ESTIMATOR_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <max_position_estimator/AddTwoIntsRequest.h>
#include <max_position_estimator/AddTwoIntsResponse.h>


namespace max_position_estimator
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace max_position_estimator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::max_position_estimator::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::max_position_estimator::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::max_position_estimator::AddTwoInts > {
  static const char* value()
  {
    return "max_position_estimator/AddTwoInts";
  }

  static const char* value(const ::max_position_estimator::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::max_position_estimator::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::max_position_estimator::AddTwoInts >
template<>
struct MD5Sum< ::max_position_estimator::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::max_position_estimator::AddTwoInts >::value();
  }
  static const char* value(const ::max_position_estimator::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::max_position_estimator::AddTwoIntsRequest> should match
// service_traits::DataType< ::max_position_estimator::AddTwoInts >
template<>
struct DataType< ::max_position_estimator::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::max_position_estimator::AddTwoInts >::value();
  }
  static const char* value(const ::max_position_estimator::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::max_position_estimator::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::max_position_estimator::AddTwoInts >
template<>
struct MD5Sum< ::max_position_estimator::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::max_position_estimator::AddTwoInts >::value();
  }
  static const char* value(const ::max_position_estimator::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::max_position_estimator::AddTwoIntsResponse> should match
// service_traits::DataType< ::max_position_estimator::AddTwoInts >
template<>
struct DataType< ::max_position_estimator::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::max_position_estimator::AddTwoInts >::value();
  }
  static const char* value(const ::max_position_estimator::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAX_POSITION_ESTIMATOR_MESSAGE_ADDTWOINTS_H
