---
name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        working-directory: ./Ausarbeitung
      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1
        working-directory: ./Ausarbeitung
        with:
          format: pdf
          filename: bericht.tex